// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.20.3
// source: protos/frontend/data/iam.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Describes the type of the client, which will indicate how it should interact with the API
type ClientType int32

const (
	ClientType_Invalid ClientType = 0 // Used when converting the enum from JSON to hold invalid values
	ClientType_Web     ClientType = 1 // For web (in-browser) clients
	ClientType_CLI     ClientType = 2 // For CLI clients
	ClientType_Other   ClientType = 3 // For clients that do not fit into either type of client
)

// Enum value maps for ClientType.
var (
	ClientType_name = map[int32]string{
		0: "Invalid",
		1: "Web",
		2: "CLI",
		3: "Other",
	}
	ClientType_value = map[string]int32{
		"Invalid": 0,
		"Web":     1,
		"CLI":     2,
		"Other":   3,
	}
)

func (x ClientType) Enum() *ClientType {
	p := new(ClientType)
	*p = x
	return p
}

func (x ClientType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_frontend_data_iam_proto_enumTypes[0].Descriptor()
}

func (ClientType) Type() protoreflect.EnumType {
	return &file_protos_frontend_data_iam_proto_enumTypes[0]
}

func (x ClientType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientType.Descriptor instead.
func (ClientType) EnumDescriptor() ([]byte, []int) {
	return file_protos_frontend_data_iam_proto_rawDescGZIP(), []int{0}
}

// Describes a Quantum client. Note that this object does not include the secret which should be used to authenticate
// the client. That particular value will only be made available once when the client is created
type Client struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ID of the client, as recorded in the system. This value should be saved for later
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The domain for which the client is registered. This value may be used to deny access to certain resources
	Domain string `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	// The type of the client. This value may be used to deny access to certain resources
	Type ClientType `protobuf:"varint,3,opt,name=type,proto3,enum=protos.frontend.data.ClientType" json:"type"` 
	// A list of links that can be used to populate data associated with this client
	Links []*Link `protobuf:"bytes,4,rep,name=links,proto3" json:"links"` 
}

func (x *Client) Reset() {
	*x = Client{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_frontend_data_iam_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_protos_frontend_data_iam_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_protos_frontend_data_iam_proto_rawDescGZIP(), []int{0}
}

func (x *Client) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Client) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Client) GetType() ClientType {
	if x != nil {
		return x.Type
	}
	return ClientType_Invalid
}

func (x *Client) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

// Describes a Quantum user. This object will not include any fields which will identify the user to our system. Instead,
// the user's ID will be extracted from the access token which is passed to authenticate them. This adds an extra layer of
// security to our system as the user is not allowed to know their own ID directly
type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The email address that the user may use when logging in
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// A list of links that can be used to populate data associated with this user
	Links []*Link `protobuf:"bytes,2,rep,name=links,proto3" json:"links"` 
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_frontend_data_iam_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_protos_frontend_data_iam_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_protos_frontend_data_iam_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

var File_protos_frontend_data_iam_proto protoreflect.FileDescriptor

var file_protos_frontend_data_iam_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x64, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x69, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x64, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x66,
	0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x98, 0x01, 0x0a, 0x06, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x34, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x30, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x66, 0x72, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x64, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x05, 0x6c,
	0x69, 0x6e, 0x6b, 0x73, 0x22, 0x54, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x30, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x6b,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x4c,
	0x69, 0x6e, 0x6b, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x2a, 0x36, 0x0a, 0x0a, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x6e, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x57, 0x65, 0x62, 0x10, 0x01, 0x12, 0x07,
	0x0a, 0x03, 0x43, 0x4c, 0x49, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x4f, 0x74, 0x68, 0x65, 0x72,
	0x10, 0x03, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x78, 0x65, 0x66, 0x69, 0x6e, 0x6f, 0x2f, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x75, 0x6d, 0x2d,
	0x61, 0x70, 0x69, 0x2d, 0x67, 0x6f, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_protos_frontend_data_iam_proto_rawDescOnce sync.Once
	file_protos_frontend_data_iam_proto_rawDescData = file_protos_frontend_data_iam_proto_rawDesc
)

func file_protos_frontend_data_iam_proto_rawDescGZIP() []byte {
	file_protos_frontend_data_iam_proto_rawDescOnce.Do(func() {
		file_protos_frontend_data_iam_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_frontend_data_iam_proto_rawDescData)
	})
	return file_protos_frontend_data_iam_proto_rawDescData
}

var file_protos_frontend_data_iam_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_frontend_data_iam_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_frontend_data_iam_proto_goTypes = []interface{}{
	(ClientType)(0), // 0: protos.frontend.data.ClientType
	(*Client)(nil),  // 1: protos.frontend.data.Client
	(*User)(nil),    // 2: protos.frontend.data.User
	(*Link)(nil),    // 3: protos.frontend.data.Link
}
var file_protos_frontend_data_iam_proto_depIdxs = []int32{
	0, // 0: protos.frontend.data.Client.type:type_name -> protos.frontend.data.ClientType
	3, // 1: protos.frontend.data.Client.links:type_name -> protos.frontend.data.Link
	3, // 2: protos.frontend.data.User.links:type_name -> protos.frontend.data.Link
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protos_frontend_data_iam_proto_init() }
func file_protos_frontend_data_iam_proto_init() {
	if File_protos_frontend_data_iam_proto != nil {
		return
	}
	file_protos_frontend_data_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protos_frontend_data_iam_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Client); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_frontend_data_iam_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_frontend_data_iam_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_frontend_data_iam_proto_goTypes,
		DependencyIndexes: file_protos_frontend_data_iam_proto_depIdxs,
		EnumInfos:         file_protos_frontend_data_iam_proto_enumTypes,
		MessageInfos:      file_protos_frontend_data_iam_proto_msgTypes,
	}.Build()
	File_protos_frontend_data_iam_proto = out.File
	file_protos_frontend_data_iam_proto_rawDesc = nil
	file_protos_frontend_data_iam_proto_goTypes = nil
	file_protos_frontend_data_iam_proto_depIdxs = nil
}
